services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: concert_town_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - db

volumes:
  postgres_data:
